local _, ns = ...  -- Namespace

ns.consts = {
    MODE_EP = 'ep',
    MODE_GP = 'gp',
    MODE_BOTH = 'both',

    SPEC_DK_BLOOD = 'Blood',
    SPEC_DK_FROST = 'Frost',
    SPEC_DK_UNHOLY = 'Unholy',
    SPEC_DRUID_BALANCE = 'Balance',
    SPEC_DRUID_FERAL = 'Feral Combat',
    SPEC_DRUID_RESTO = 'Restoration',
    SPEC_HUNTER_BM = 'Beast Mastery',
    SPEC_HUNTER_MM = 'Marksmanship',
    SPEC_HUNTER_SV = 'Survival',
    SPEC_MAGE_ARCANE = 'Arcane',
    SPEC_MAGE_FIRE = 'Fire',
    SPEC_MAGE_FROST = 'Frost',
    SPEC_PALADIN_HOLY = 'Holy',
    SPEC_PALADIN_PROT = 'Protection',
    SPEC_PALADIN_RET = 'Retribution',
    SPEC_PRIEST_DISC = 'Discipline',
    SPEC_PRIEST_HOLY = 'Holy',
    SPEC_PRIEST_SHADOW = 'Shadow',
    SPEC_ROGUE_ASS = 'Assassination',
    SPEC_ROGUE_COMBAT = 'Combat',
    SPEC_ROGUE_SUB = 'Subtlety',
    SPEC_SHAMAN_ELE = 'Elemental',
    SPEC_SHAMAN_ENH = 'Enhancement',
    SPEC_SHAMAN_RESTO = 'Restoration',
    SPEC_WARLOCK_AFF = 'Affliction',
    SPEC_WARLOCK_DEMO = 'Demonology',
    SPEC_WARLOCK_DESTRO = 'Destruction',
    SPEC_WARRIOR_ARMS = 'Arms',
    SPEC_WARRIOR_FURY = 'Fury',
    SPEC_WARRIOR_PROT = 'Protection',
}
